### ISSUE TITLE
Muted users will still able to speak on threads channels, and also add reactions to messages.

### ISSUE THREAD

**Issue by Klairm** [makigas/clank#417]
**Describe the bug**
When an user is muted, he will still be able to add reactions on message, also it will be able to speak on thread channels.

**To Reproduce**
Mute an user, an check that the user is still able to add reactions and talk in threads.

**Expected behavior**
Muted users shouldn't be able to speak in any way, not even communicating via reactions

**Additional context**
hola buenas tardes

**Comment by danirod** [comment]
This is a misconfiguration of the server permissions that has since then been fixed. Due to some channel overrides, some settings were not applying to all the channels. In particular:

* Muted cannot react anymore.
* Thread channels have their own settings and they were never configured.

In regards to the channels with overrides, Discord channel overrides are complex. Given a configuration such as:

```
@Muted -> Red
@Interesado -> Green
@everyone -> Red
```

Someone not in Interesado will not able to send messages. Someone in Interesado will be able to send messages because green overrides red; but someone in Interesado + Muted will still be able to send messages because a green permission is more powerful than a red permission -- in other words, it doesn't matter how many roles put a red permission on that, as long as any of the member roles is green, the user will be able to talk even if there is a red permission with an higher priority.

The solution to prevent messages from being sent to the #hice-esto and #enlaces channels, which already make use of the red-green system to only allow members of specific roles to send messages, is to entirely disable the "View channel" permission for muted members, which will prevent them from seeing the channel, in case a level 2 member has to be muted.
